// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scsp.proto

package scsp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClipBoardMessage struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClipBoardMessage) Reset()         { *m = ClipBoardMessage{} }
func (m *ClipBoardMessage) String() string { return proto.CompactTextString(m) }
func (*ClipBoardMessage) ProtoMessage()    {}
func (*ClipBoardMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_scsp_354b7029f7ddc6ae, []int{0}
}
func (m *ClipBoardMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClipBoardMessage.Unmarshal(m, b)
}
func (m *ClipBoardMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClipBoardMessage.Marshal(b, m, deterministic)
}
func (dst *ClipBoardMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClipBoardMessage.Merge(dst, src)
}
func (m *ClipBoardMessage) XXX_Size() int {
	return xxx_messageInfo_ClipBoardMessage.Size(m)
}
func (m *ClipBoardMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClipBoardMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClipBoardMessage proto.InternalMessageInfo

func (m *ClipBoardMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ClipBoardMessage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type ClipBoardResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClipBoardResp) Reset()         { *m = ClipBoardResp{} }
func (m *ClipBoardResp) String() string { return proto.CompactTextString(m) }
func (*ClipBoardResp) ProtoMessage()    {}
func (*ClipBoardResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_scsp_354b7029f7ddc6ae, []int{1}
}
func (m *ClipBoardResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClipBoardResp.Unmarshal(m, b)
}
func (m *ClipBoardResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClipBoardResp.Marshal(b, m, deterministic)
}
func (dst *ClipBoardResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClipBoardResp.Merge(dst, src)
}
func (m *ClipBoardResp) XXX_Size() int {
	return xxx_messageInfo_ClipBoardResp.Size(m)
}
func (m *ClipBoardResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClipBoardResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClipBoardResp proto.InternalMessageInfo

type RegisterMessage struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterMessage) Reset()         { *m = RegisterMessage{} }
func (m *RegisterMessage) String() string { return proto.CompactTextString(m) }
func (*RegisterMessage) ProtoMessage()    {}
func (*RegisterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_scsp_354b7029f7ddc6ae, []int{2}
}
func (m *RegisterMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterMessage.Unmarshal(m, b)
}
func (m *RegisterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterMessage.Marshal(b, m, deterministic)
}
func (dst *RegisterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterMessage.Merge(dst, src)
}
func (m *RegisterMessage) XXX_Size() int {
	return xxx_messageInfo_RegisterMessage.Size(m)
}
func (m *RegisterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterMessage proto.InternalMessageInfo

func (m *RegisterMessage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RegisterResp struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_scsp_354b7029f7ddc6ae, []int{3}
}
func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (dst *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(dst, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type PingMessage struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_scsp_354b7029f7ddc6ae, []int{4}
}
func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (dst *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(dst, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PingMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PingResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResp) Reset()         { *m = PingResp{} }
func (m *PingResp) String() string { return proto.CompactTextString(m) }
func (*PingResp) ProtoMessage()    {}
func (*PingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_scsp_354b7029f7ddc6ae, []int{5}
}
func (m *PingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResp.Unmarshal(m, b)
}
func (m *PingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResp.Marshal(b, m, deterministic)
}
func (dst *PingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResp.Merge(dst, src)
}
func (m *PingResp) XXX_Size() int {
	return xxx_messageInfo_PingResp.Size(m)
}
func (m *PingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResp.DiscardUnknown(m)
}

var xxx_messageInfo_PingResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClipBoardMessage)(nil), "ClipBoardMessage")
	proto.RegisterType((*ClipBoardResp)(nil), "ClipBoardResp")
	proto.RegisterType((*RegisterMessage)(nil), "RegisterMessage")
	proto.RegisterType((*RegisterResp)(nil), "RegisterResp")
	proto.RegisterType((*PingMessage)(nil), "PingMessage")
	proto.RegisterType((*PingResp)(nil), "PingResp")
}

func init() { proto.RegisterFile("scsp.proto", fileDescriptor_scsp_354b7029f7ddc6ae) }

var fileDescriptor_scsp_354b7029f7ddc6ae = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xc9, 0x94, 0x6d, 0x3d, 0xeb, 0xdc, 0xcc, 0x55, 0x29, 0x82, 0x23, 0x57, 0x85, 0x61,
	0x10, 0x7d, 0x03, 0x87, 0x37, 0x82, 0x30, 0xd2, 0x27, 0x88, 0xed, 0xa1, 0x04, 0xb6, 0x26, 0xe4,
	0x04, 0xc1, 0x57, 0xf0, 0xa9, 0x25, 0x85, 0xe8, 0xda, 0x1b, 0x2f, 0xff, 0xf0, 0xe7, 0x3b, 0xe7,
	0x4b, 0x00, 0xa8, 0x21, 0x27, 0x9d, 0xb7, 0xc1, 0x8a, 0x37, 0xd8, 0x1e, 0x4e, 0xc6, 0xbd, 0x58,
	0xed, 0xdb, 0x77, 0x24, 0xd2, 0x1d, 0xf2, 0x3b, 0xc8, 0x82, 0x39, 0x23, 0x05, 0x7d, 0x76, 0x05,
	0xdb, 0xb1, 0xea, 0x4a, 0xfd, 0x1d, 0xf0, 0x02, 0x16, 0x8d, 0xed, 0x03, 0xf6, 0xa1, 0x98, 0xed,
	0x58, 0x95, 0xab, 0x14, 0xc5, 0x06, 0xd6, 0xbf, 0x2c, 0x85, 0xe4, 0xc4, 0x1e, 0x36, 0x0a, 0x3b,
	0x43, 0x01, 0x7d, 0x62, 0x17, 0xb0, 0xd0, 0x6d, 0xeb, 0x91, 0x68, 0x20, 0x67, 0x2a, 0x45, 0x51,
	0x41, 0x9e, 0xca, 0xf1, 0x72, 0x6c, 0x3a, 0xfd, 0x75, 0xb2, 0xba, 0x1d, 0x9a, 0xb9, 0x4a, 0x51,
	0xbc, 0xc2, 0xea, 0x68, 0xfa, 0xee, 0x5f, 0xe4, 0x58, 0x64, 0x36, 0x11, 0x11, 0x00, 0xcb, 0x88,
	0x89, 0xc3, 0x9e, 0xbe, 0x19, 0xac, 0xea, 0x43, 0x7d, 0xac, 0xd1, 0x7f, 0x9a, 0x06, 0xf9, 0x1e,
	0xe6, 0x0a, 0x9d, 0xf5, 0x81, 0xdf, 0xca, 0xe9, 0xfb, 0x94, 0x37, 0x72, 0xa4, 0xc9, 0x1f, 0x60,
	0x99, 0x36, 0xe7, 0x5b, 0x39, 0x31, 0x2e, 0xd7, 0xf2, 0x52, 0xeb, 0x91, 0xf1, 0x7b, 0xb8, 0x8e,
	0x73, 0x79, 0x2e, 0x2f, 0x2c, 0xca, 0x4c, 0xa6, 0x65, 0x3e, 0xe6, 0xc3, 0xd7, 0x3c, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x56, 0x1b, 0x5e, 0xc1, 0xa8, 0x01, 0x00, 0x00,
}
