// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package scsp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SCSPServiceClient is the client API for SCSPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SCSPServiceClient interface {
	Report(ctx context.Context, in *ClipBoardMessage, opts ...grpc.CallOption) (*ClipBoardResp, error)
	Register(ctx context.Context, in *RegisterMessage, opts ...grpc.CallOption) (SCSPService_RegisterClient, error)
}

type sCSPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSCSPServiceClient(cc grpc.ClientConnInterface) SCSPServiceClient {
	return &sCSPServiceClient{cc}
}

func (c *sCSPServiceClient) Report(ctx context.Context, in *ClipBoardMessage, opts ...grpc.CallOption) (*ClipBoardResp, error) {
	out := new(ClipBoardResp)
	err := c.cc.Invoke(ctx, "/SCSPService/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sCSPServiceClient) Register(ctx context.Context, in *RegisterMessage, opts ...grpc.CallOption) (SCSPService_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &SCSPService_ServiceDesc.Streams[0], "/SCSPService/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &sCSPServiceRegisterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SCSPService_RegisterClient interface {
	Recv() (*RegisterResp, error)
	grpc.ClientStream
}

type sCSPServiceRegisterClient struct {
	grpc.ClientStream
}

func (x *sCSPServiceRegisterClient) Recv() (*RegisterResp, error) {
	m := new(RegisterResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SCSPServiceServer is the server API for SCSPService service.
// All implementations must embed UnimplementedSCSPServiceServer
// for forward compatibility
type SCSPServiceServer interface {
	Report(context.Context, *ClipBoardMessage) (*ClipBoardResp, error)
	Register(*RegisterMessage, SCSPService_RegisterServer) error
	mustEmbedUnimplementedSCSPServiceServer()
}

// UnimplementedSCSPServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSCSPServiceServer struct {
}

func (UnimplementedSCSPServiceServer) Report(context.Context, *ClipBoardMessage) (*ClipBoardResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedSCSPServiceServer) Register(*RegisterMessage, SCSPService_RegisterServer) error {
	return status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSCSPServiceServer) mustEmbedUnimplementedSCSPServiceServer() {}

// UnsafeSCSPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SCSPServiceServer will
// result in compilation errors.
type UnsafeSCSPServiceServer interface {
	mustEmbedUnimplementedSCSPServiceServer()
}

func RegisterSCSPServiceServer(s grpc.ServiceRegistrar, srv SCSPServiceServer) {
	s.RegisterService(&SCSPService_ServiceDesc, srv)
}

func _SCSPService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipBoardMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SCSPServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SCSPService/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SCSPServiceServer).Report(ctx, req.(*ClipBoardMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SCSPService_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SCSPServiceServer).Register(m, &sCSPServiceRegisterServer{stream})
}

type SCSPService_RegisterServer interface {
	Send(*RegisterResp) error
	grpc.ServerStream
}

type sCSPServiceRegisterServer struct {
	grpc.ServerStream
}

func (x *sCSPServiceRegisterServer) Send(m *RegisterResp) error {
	return x.ServerStream.SendMsg(m)
}

// SCSPService_ServiceDesc is the grpc.ServiceDesc for SCSPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SCSPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SCSPService",
	HandlerType: (*SCSPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _SCSPService_Report_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _SCSPService_Register_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scsp.proto",
}
