[package]
name = "scsp-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
rocket = {version = "0.5.0", features=["json"]}
scsp = {path = "../..", version="0.1.0"}
log = "0.4"
simple_logger = "4.3.3"